### ISSUE TITLE
the underscore in com.barista_v fails to find

### ISSUE THREAD

**Issue by mwinters-stuff** [nullindustries/Android-UltraRecyclerView#9]
I had just tried to update, to the new package name. When gradle is syncing it fails to find the package in jcenter.

I uploaded it to my local (apache archiva) repository and it still couldnt find it.

I then uploaded with the groupid com.baristav, which does not have the underscore and gradle is finding the package.

Looks like gradle, (version 2.11) doesnt like the underscore in the name, this is the only package I have found that uses one.
?

**Comment by Rajan** [comment]
I faced the same issue.
